### ISSUE TITLE
screenshot on chrome extension is not working

### ISSUE THREAD

**Issue by willi84** [stilliard/quick-add-github-issue-browser-extension#5]

**Comment by stilliard** [comment]
Hi @willi84 
Sorry for the delayed reply here. 
You're right, looks like that's breaking atm, I'll see what I can do to resolve it :+1:

**Comment by stilliard** [comment]
Found the issue, looks like it was redirecting to github too quickly when screenshot was selected, added a 300ms delay to resolve it. 
Publishing a new version now.

**Comment by stilliard** [comment]
Code updated here ref 9bdd808e8c0cf0c07ddc3700bed897496b9c26d8

I've also submitted the new package but looks like it's got to go through review again so expect it'll be a few days before it appears updated in the store for updates.

**Comment by stilliard** [comment]
New version is now published :smiley: 

Thanks again @willi84 for the report.
