### ISSUE TITLE
Permissions too broad

### ISSUE THREAD

**Issue by vHanda** [stilliard/quick-add-github-issue-browser-extension#6]
Hey. This extension seems awesome. However I'm not keen on giving it permissions to access my my activity. Is there any way the permissions could be made tighter?

(Or otherwise just explain why such permissions are required)

**Comment by stilliard** [comment]
Hi @vHanda 

The permission model for the extensions forces it to be broad unfortunately.
But if it helps, here's my justifications supplied to Google's review team.

![image](https://user-images.githubusercontent.com/77454/117794753-71671280-b245-11eb-9f98-2ab4ffb2b7a8.png)

Hope this helps clarify everything.

If you're interested too, all the code is here & open source. You can not only review it but you can also fork it and customise to your own needs too :+1:
